import Link from "next/link"
import React from "react"
import { getAllPostsMeta } from "../../lib/mdx"

export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
}

const BlogPage = async () => {
  const posts = await getAllPostsMeta()

  return (
    <main className="grid h-screen place-items-center">
      <div className="flex flex-row space-x-2">
        {posts?.map((post) => (
          <Link
            href={`blog/${post.slug}`}
            key={post?.title}
            className="p-8 rounded-md shadow-md bg-white"
          >
            <h3 className="text-xl font-semibold">{post.title}</h3>
            <p className="mt-4 text-sm">{post.author}</p>
            <time className="text-[12px] text-gray-400">
              {post.publishDate}
            </time>
          </Link>
        ))}
      </div>
    </main>
  )
}

export default BlogPage
