import React from "react"
import Link from "next/link"
import Image from "next/image"
import { getAllPostsMeta } from "../../lib/mdx"

export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
}

const BlogPage = async () => {
  const posts = await getAllPostsMeta()

  return (
    <main className="mx-auto w-full flex max-w-3xl flex-1">
      <div className="flex flex-col space-y-4 py-24 px-6 md:px-0 sm:py-28 md:space-y-0 flex-grow">
        <h1 className="text-black text-4xl font-bold md:pb-4 md:text-6xl ">
          All Posts.
        </h1>
        <div className="flex flex-col space-y-2">
          {posts?.map((post) => (
            <div key={post?.title} className="flex-grow">
              <Link
                href={`blog/${post.slug}`}
                className="block p-8 rounded-md shadow-md bg-white hover:bg-neutral-100"
              >
                <div className="flex flex-row space-x-2 items-center">
                  <div className="w-1/4">
                    <Image
                      src={post.image!}
                      alt=""
                      width={125}
                      height={125}
                      className="rounded-md"
                      priority
                    />
                  </div>
                  <div className="w-3/4">
                    <h3 className="text-2xl font-semibold">{post.title}</h3>
                    <div className="flex flex-row space-x-2 items-center my-1 text-sm text-neutral-500">
                      <time>{post.publishDate}</time>
                      <span>&middot;</span>
                      <p>{post.minuteRead}</p>
                    </div>
                    <p className="text-sm">{post.description}</p>
                  </div>
                </div>
              </Link>
            </div>
          ))}
        </div>
      </div>
    </main>
  )
}

export default BlogPage
