import React from "react"
import { getAllPostsMeta } from "../../lib/mdx"
import Link from "next/link"

export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
}

const BlogPage = async () => {
  const posts = await getAllPostsMeta()

  return (
    <main className="mx-auto w-full flex max-w-3xl flex-1">
      <div className="flex flex-col space-y-4 py-24 px-6 md:px-0 sm:py-28 md:space-y-0 flex-grow">
        <h1 className="text-black text-4xl font-bold md:pb-4 md:text-6xl ">
          All Posts.
        </h1>
        <div className="flex flex-col space-y-2">
          {posts?.map((post) => (
            <div key={post?.title} className="flex-grow">
              <Link
                href={`blog/${post.slug}`}
                className="block p-8 rounded-md shadow-md bg-white hover:bg-neutral-100"
              >
                <h3 className="text-xl font-semibold">{post.title}</h3>
                <p className="mt-4 text-sm">{post.author}</p>
                <time className="text-[12px] text-gray-400">
                  {post.publishDate}
                </time>
              </Link>
            </div>
          ))}
        </div>
      </div>
    </main>
  )
}

export default BlogPage
