import React from "react";
import Link from "next/link";
import Image from "next/image";
import { getAllPostsMeta } from "../lib/mdx";
import { HiOutlineArrowNarrowRight } from "react-icons/hi";

export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

const BlogPage = async () => {
  const posts = await getAllPostsMeta();

  return (
    <main className="mx-auto w-full flex max-w-3xl flex-1">
      <div className="flex flex-col space-y-4 py-24 px-6 md:px-0 sm:py-28 md:space-y-0 flex-grow">
        <h1 className="text-white text-3xl font-bold md:pb-4 md:text-5xl">
          Latest Posts.
        </h1>
        <div className="flex flex-col space-y-4">
          {posts?.map((post) => (
            <div
              key={post?.title}
              className="flex-grow py-4 text-white border-b border-neutral-400"
            >
              {post?.image !== "" ? (
                <div className="flex flex-col">
                  <div className="flex flex-row space-x-2 items-center">
                    <div className="w-full md:w-3/4">
                      <h3 className="text-xl md:text-2xl font-semibold">
                        {post.title}
                      </h3>
                      <div className="flex flex-row space-x-2 items-center my-1 text-sm text-neutral-400">
                        <time>{post.publishDate}</time>
                        <span>&middot;</span>
                        <p>{post.minuteRead}</p>
                      </div>
                      <p className="text-sm">{post.description}</p>
                    </div>
                    <div className="hidden md:block md:w-1/4">
                      <Image
                        src={post.image!}
                        alt=""
                        width={125}
                        height={125}
                        className="rounded-md bg-cover"
                        priority
                      />
                    </div>
                  </div>
                  <Link href={`/${post.slug}`} className="group">
                    <div className="flex flex-row items-center space-x-2 mt-2">
                      <span className="text-stone-200 group-hover:text-stone-400">
                        Read more
                      </span>
                      <HiOutlineArrowNarrowRight
                        size={25}
                        className="mt-1 group-hover:translate-x-1 duration-300 text-stone-200 group-hover:text-stone-400"
                      />
                    </div>
                  </Link>
                </div>
              ) : (
                <div className="flex flex-col">
                  <div className="flex flex-row space-x-2 items-center">
                    <div className="w-full md:w-3/4">
                      <h3 className="text-xl md:text-2xl font-semibold">
                        {post.title}
                      </h3>
                      <div className="flex flex-row space-x-2 items-center my-1 text-sm text-neutral-400">
                        <time>{post.publishDate}</time>
                        <span>&middot;</span>
                        <p>{post.minuteRead}</p>
                      </div>
                      <p className="text-sm">{post.description}</p>
                    </div>
                  </div>

                  <Link href={`/${post.slug}`} className="group">
                    <div className="flex flex-row items-center space-x-2 mt-2">
                      <span className="text-stone-200 group-hover:text-stone-400">
                        Read more
                      </span>
                      <HiOutlineArrowNarrowRight
                        size={25}
                        className="mt-1 group-hover:translate-x-1 duration-300 text-stone-200 group-hover:text-stone-400"
                      />
                    </div>
                  </Link>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </main>
  );
};

export default BlogPage;
